### PR TITLE
Fix formatter to add a new line after the preprocessor directives part

### PR DESCRIPTION
**Pull request by keyhr**
Fix for #38

### CODE REVIEW

**Comment by keyhr** [comment]
I'm not sure why the test fails with python 3.6 on ubuntu-latest

**Comment by cacharle** [comment]
I have no idea why the CI is failing, I looked in the file where there is the python versions (from the CI logs) and there is v3.6 in there.

I tried to rerun but didn't work.

**Comment by cacharle** [comment]
Also, the main repo has the pypi api key now, so u can make your PRs there.

I asked @dawnbeen to make you contributor so you're more free if you want to make more contributions.

**Comment by cacharle** [comment]
I just looked it up and Python3.6 has reached end of life a year ago so we can just drop it from the CI.

**Comment by keyhr** [comment]
> I asked @dawnbeen to make you contributor so you're more free if you want to make more contributions.

OK, sorry to bother you. Should I move this PR to [this repo](https://github.com/dawnbeen/c_formatter_42)?

**Comment by cacharle** [comment]
It's no problem, I'm glad you're fixing issues.

I don't know if you can transfer PRs cleanly.. Otherwise it's probably easier for both you and me if you delete it here and open a new one in the main repo (I'll probably delete this fork anyway)

**Comment by keyhr** [comment]
>> I have no idea why the CI is failing, I looked in the file where there is the python versions (from the CI logs) and there is v3.6 in there.
I tried to rerun but didn't work.
>
> I just looked it up and Python3.6 has reached end of life a year ago so we can just drop it from the CI.

That makes sense... I didn't know that Python3.6 no longer being supported.

**Comment by keyhr** [comment]
Saying "move this PR", I meant opening a new one on the main repo. (I don't know any other way to do it...)

**Comment by keyhr** [comment]
By the way, I'm no longer 42 student anymore too, so I contribute when I feel like it. Perhaps I will ask for some review again.

**Comment by cacharle** [comment]
> By the way, I'm no longer 42 student anymore too, so I contribute when I feel like it. Perhaps I will ask for some review again.

Yeah, don't worry

**Comment by keyhr** [comment]
Do you think these commits fix the issue?

**Comment by cacharle** [comment]
Looks good, you added tests and didn't break other tests

**Comment by keyhr** [comment]
OK, thanks.

It looks that I don't have 'write' permission on the main branch. I've just made PR but cannot merge it. I'm not sure how to make changes to the main repo...

**Comment by cacharle** [comment]
Yeah, I asked @dawnbeen by mail 5min ago so you probably don't have access right now :sweat_smile: but you'll receive a notification of mail as soon as she gives you access (I can't give you access myself)

I'll merge your stuff in the main branch in the meantime.

**Comment by keyhr** [comment]
"A watched pot never boils" is very very right for me 😇
Thank you very much.

**Pull request closed without merging**
