### PR TITLE
[update] revised readme

### PR DESCRIPTION
**Pull request by keyhr**
- Usage in vscode
- Python requirement
- Installation

### CODE REVIEW

**Comment by cacharle** [comment]
Hi, (sorry I'm using those comments to communicate random info to you)

As you can see I switched the Github CI/CD, right now I only have testing on python versions >=3.6.
I think I can setup automatic deployment to pypi every time you tag a commit with a version number.

Feel free to reach me at <me@cacharle.xyz> if you have any question

**Comment by cacharle** [comment]
Ok, it will deploy to pypi (https://pypi.org/project/c-formatter-42/) every time you create a release (which needs a tagged commit).

I'll figure out how to automatically create a release when a tag is created later.

You can publish to pypi without any assistance from me which is good enough for now

**Comment by cacharle** [comment]
don't forget to update the version in the [setup.cfg](https://github.com/cacharle/c_formatter_42/blob/master/setup.cfg) file before you deploy it

**Comment by keyhr** [comment]
Thanks, sounds nice that I can update the pypi package to adapt to norminette v3!

By the way, is it ok that the test runs every time I push the changes even if on readme or some files not affecting the formatter? I'm just worried that I could waste or be wasting your github action spending limit (3000 minutes per month for pro account).

**Comment by cacharle** [comment]
Never used github actions before, didn't knew their was a limit :sweat_smile:
 
I think it's ok for now since I'm not using them for anything else and 3000min seems plenty enough for this one, even on every commit.

If the issue arise in the future, I'll limit the CI/CD on a `publish` branch or something.

**Comment by keyhr** [comment]
Hi there, (sorry for still sending message here, next time I'll use e-mail)

I've just published v0.1.0 and pypi package seemed to be created with no fail. Cheers ^^

I didn't knew about the limit, too. 😅
Noted that I don't have to care too much about use of CI/CD for now. (I don't think I'll commit so many time though)

**Comment by cacharle** [comment]
Thank you for your contributions, hope the tool will serve you well :grinning:

**Pull request closed without merging**
